esphome:
  name: solis
  friendly_name: solis

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0
  level: debug

# Enable Home Assistant API
api:

ota:
  password: "06e5385a867b05530f6312b74e2c5880"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Fallback Hotspot"
    password: "configesp"

uart:
  id: mod_bus
  tx_pin: D7
  rx_pin: D6
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: D5
  id: modbus1
  send_wait_time: 1000ms

modbus_controller:
- id: ginlong
  modbus_id: modbus1
  setup_priority: -10
  update_interval: 60s

sensor:
- platform: modbus_controller
  modbus_controller_id: ginlong
  name: "Temperatuur omvormer"
  address: 3041
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: °C
  device_class: temperature
  state_class: measurement
  filters:
  - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: ginlong
  name: "GenerationToday"
  address: 3014
  register_type: read
  value_type: U_WORD
  accuracy_decimals: 1
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
  filters:
  - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: ginlong
  name: "GenerationTotal"
  address: 3008
  register_type: read
  value_type: U_DWORD
  unit_of_measurement: kWh
  device_class: energy

- platform: modbus_controller
  modbus_controller_id: ginlong
  name: "DC_PV1"
  address: 3021
  register_type: read
  value_type: U_WORD
  unit_of_measurement: V
  device_class: energy
  filters:
  - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: ginlong
  name: "DC_PV2"
  address: 3023
  register_type: read
  value_type: U_WORD
  unit_of_measurement: V
  device_class: energy
  filters:
  - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: ginlong
  name: "ActualPower"
  address: 3004
  register_type: read
  value_type: U_DWORD
  unit_of_measurement: W
  device_class: energy

  #- platform: modbus_controller
  #  modbus_controller_id: ginlong
  #  name: "AC Volt"
  #  address: 3035
  #  register_type: read
  #  value_type: U_WORD
  #  unit_of_measurement: V
  #  device_class: energy
  #  filters:
  #  - multiply: 0.1

#- platform: modbus_controller
#  modbus_controller_id: ginlong
#  name: "AC Current"
#  address: 3038
#  register_type: read
#  value_type: U_WORD
#  unit_of_measurement: A
#  device_class: energy

#- platform: modbus_controller
#  modbus_controller_id: ginlong
#  name: "AC Frequency"
#  address: 3042
#  register_type: read
#  value_type: U_WORD
#  unit_of_measurement: Hz
#  device_class: energy
#  filters:
#  - multiply: 0.01